### ISSUE TITLE
Update Contributors filter to reflect merge commits

### ISSUE THREAD

**Issue by poidag-zz** [plunder-app/plndr-cloud-provider#23]

**Comment by plunder-app** [comment]
Can you check -> 

https://docs.github.com/en/github/visualizing-repository-data-with-graphs/viewing-a-projects-contributors#troubleshooting-contributors

You should be appearing into the contributors.

**Comment by plunder-app** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/46795316/89181669-7bf8cb00-d594-11ea-881f-30137c96131d.png">

The commit appears to come from a different address.

**Comment by thebsdbox** [comment]
As this is an issue not related to the project, I'll close this issue. Feel free to comment if that's wrong.
